### ISSUE TITLE
post_build only builds after the whole workspace has built - it should be applied after the crate is built

### ISSUE THREAD

**Issue by kylezs** [phil-opp/cargo-post#25]
When using workspaces where you might have one build depend on another, it makes sense that you may want to use post-build on that, so that the dependencies can use the modified post-build. However, currently it post builds only after the whole workspace's `cargo build` is complete.

**Comment by phil-opp** [comment]
Thanks for the request! I agree that this would be nice, but unfortunately not compatible with the current design of this tool.

We currently run the cargo command without any modification and just add an additional step afterwards. This ensures that the build behavior stays exactly the same as with the bare cargo command.

To run post build scripts after each crate, we would need to do some more complex manipulations of the given cargo command. For example, when `--workspace` is given as an argument, we would need to translate this to several `--package` commands. The difficult part is to keep the behavior the same because cargo does some dependency and feature unification when multiple crates are built at once. I'm not sure whether it's even possible to match cargo's behavior exactly without forking `cargo`.

I don't have the time to implement and/or maintain such functionality, so I'm gonna close this request as "not planned". Feel free to fork this crate if you like to implement it yourself.
